server:
  port: 8080

spring:
  profiles:
    active: dev


logging:
  level: trace
---
#开发环境

spring:
  profiles: dev
server:
  port: 8081





---
##生产环境
spring:
  profiles: prod

server:
  port: 80
